version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - parser_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  parser:
    build: ./script
    container_name: parser
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: db
    command: ["python", "first.py"]
    networks:
      - parser_network
    env_file:
      - .env

volumes:
  db_data:

networks:
  parser_network:
    driver: bridge
